version: '3'
services:
  db:
    container_name: course-app-db
    image: postgres:15
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  web:
    container_name: Course-app
    build: .
    restart: always
    ports:
      - "8095:8095"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fazik_db
      SPRING_DATASOURCE_USERNAME: fazik_user
      SPRING_DATASOURCE_PASSWORD: root